# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/eighthundred/Downloads/clion-2019.3.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/eighthundred/Downloads/clion-2019.3.4/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eighthundred/Codes/Etbase

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eighthundred/Codes/Etbase

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/eighthundred/Downloads/clion-2019.3.4/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/eighthundred/Downloads/clion-2019.3.4/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eighthundred/Codes/Etbase/CMakeFiles /home/eighthundred/Codes/Etbase/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eighthundred/Codes/Etbase/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Server

# Build rule for target.
Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Server
.PHONY : Server

# fast build rule for target.
Server/fast:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/build
.PHONY : Server/fast

#=============================================================================
# Target rules for targets named Client

# Build rule for target.
Client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Client
.PHONY : Client

# fast build rule for target.
Client/fast:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/build
.PHONY : Client/fast

#=============================================================================
# Target rules for targets named Etbase

# Build rule for target.
Etbase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Etbase
.PHONY : Etbase

# fast build rule for target.
Etbase/fast:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/build
.PHONY : Etbase/fast

#=============================================================================
# Target rules for targets named Test

# Build rule for target.
Test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test
.PHONY : Test

# fast build rule for target.
Test/fast:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/build
.PHONY : Test/fast

Etbase/Epoll.o: Etbase/Epoll.cpp.o

.PHONY : Etbase/Epoll.o

# target to build an object file
Etbase/Epoll.cpp.o:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Epoll.cpp.o
.PHONY : Etbase/Epoll.cpp.o

Etbase/Epoll.i: Etbase/Epoll.cpp.i

.PHONY : Etbase/Epoll.i

# target to preprocess a source file
Etbase/Epoll.cpp.i:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Epoll.cpp.i
.PHONY : Etbase/Epoll.cpp.i

Etbase/Epoll.s: Etbase/Epoll.cpp.s

.PHONY : Etbase/Epoll.s

# target to generate assembly for a file
Etbase/Epoll.cpp.s:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Epoll.cpp.s
.PHONY : Etbase/Epoll.cpp.s

Etbase/Event.o: Etbase/Event.cpp.o

.PHONY : Etbase/Event.o

# target to build an object file
Etbase/Event.cpp.o:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Event.cpp.o
.PHONY : Etbase/Event.cpp.o

Etbase/Event.i: Etbase/Event.cpp.i

.PHONY : Etbase/Event.i

# target to preprocess a source file
Etbase/Event.cpp.i:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Event.cpp.i
.PHONY : Etbase/Event.cpp.i

Etbase/Event.s: Etbase/Event.cpp.s

.PHONY : Etbase/Event.s

# target to generate assembly for a file
Etbase/Event.cpp.s:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Event.cpp.s
.PHONY : Etbase/Event.cpp.s

Etbase/EventMap.o: Etbase/EventMap.cpp.o

.PHONY : Etbase/EventMap.o

# target to build an object file
Etbase/EventMap.cpp.o:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/EventMap.cpp.o
.PHONY : Etbase/EventMap.cpp.o

Etbase/EventMap.i: Etbase/EventMap.cpp.i

.PHONY : Etbase/EventMap.i

# target to preprocess a source file
Etbase/EventMap.cpp.i:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/EventMap.cpp.i
.PHONY : Etbase/EventMap.cpp.i

Etbase/EventMap.s: Etbase/EventMap.cpp.s

.PHONY : Etbase/EventMap.s

# target to generate assembly for a file
Etbase/EventMap.cpp.s:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/EventMap.cpp.s
.PHONY : Etbase/EventMap.cpp.s

Etbase/EventQueue.o: Etbase/EventQueue.cpp.o

.PHONY : Etbase/EventQueue.o

# target to build an object file
Etbase/EventQueue.cpp.o:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/EventQueue.cpp.o
.PHONY : Etbase/EventQueue.cpp.o

Etbase/EventQueue.i: Etbase/EventQueue.cpp.i

.PHONY : Etbase/EventQueue.i

# target to preprocess a source file
Etbase/EventQueue.cpp.i:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/EventQueue.cpp.i
.PHONY : Etbase/EventQueue.cpp.i

Etbase/EventQueue.s: Etbase/EventQueue.cpp.s

.PHONY : Etbase/EventQueue.s

# target to generate assembly for a file
Etbase/EventQueue.cpp.s:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/EventQueue.cpp.s
.PHONY : Etbase/EventQueue.cpp.s

Etbase/Mutex.o: Etbase/Mutex.cpp.o

.PHONY : Etbase/Mutex.o

# target to build an object file
Etbase/Mutex.cpp.o:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Mutex.cpp.o
.PHONY : Etbase/Mutex.cpp.o

Etbase/Mutex.i: Etbase/Mutex.cpp.i

.PHONY : Etbase/Mutex.i

# target to preprocess a source file
Etbase/Mutex.cpp.i:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Mutex.cpp.i
.PHONY : Etbase/Mutex.cpp.i

Etbase/Mutex.s: Etbase/Mutex.cpp.s

.PHONY : Etbase/Mutex.s

# target to generate assembly for a file
Etbase/Mutex.cpp.s:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Mutex.cpp.s
.PHONY : Etbase/Mutex.cpp.s

Etbase/Reactor.o: Etbase/Reactor.cpp.o

.PHONY : Etbase/Reactor.o

# target to build an object file
Etbase/Reactor.cpp.o:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Reactor.cpp.o
.PHONY : Etbase/Reactor.cpp.o

Etbase/Reactor.i: Etbase/Reactor.cpp.i

.PHONY : Etbase/Reactor.i

# target to preprocess a source file
Etbase/Reactor.cpp.i:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Reactor.cpp.i
.PHONY : Etbase/Reactor.cpp.i

Etbase/Reactor.s: Etbase/Reactor.cpp.s

.PHONY : Etbase/Reactor.s

# target to generate assembly for a file
Etbase/Reactor.cpp.s:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Reactor.cpp.s
.PHONY : Etbase/Reactor.cpp.s

Etbase/Socket.o: Etbase/Socket.cpp.o

.PHONY : Etbase/Socket.o

# target to build an object file
Etbase/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Socket.cpp.o
.PHONY : Etbase/Socket.cpp.o

Etbase/Socket.i: Etbase/Socket.cpp.i

.PHONY : Etbase/Socket.i

# target to preprocess a source file
Etbase/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Socket.cpp.i
.PHONY : Etbase/Socket.cpp.i

Etbase/Socket.s: Etbase/Socket.cpp.s

.PHONY : Etbase/Socket.s

# target to generate assembly for a file
Etbase/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Socket.cpp.s
.PHONY : Etbase/Socket.cpp.s

Etbase/String.o: Etbase/String.cpp.o

.PHONY : Etbase/String.o

# target to build an object file
Etbase/String.cpp.o:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/String.cpp.o
.PHONY : Etbase/String.cpp.o

Etbase/String.i: Etbase/String.cpp.i

.PHONY : Etbase/String.i

# target to preprocess a source file
Etbase/String.cpp.i:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/String.cpp.i
.PHONY : Etbase/String.cpp.i

Etbase/String.s: Etbase/String.cpp.s

.PHONY : Etbase/String.s

# target to generate assembly for a file
Etbase/String.cpp.s:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/String.cpp.s
.PHONY : Etbase/String.cpp.s

Etbase/TcpClient.o: Etbase/TcpClient.cpp.o

.PHONY : Etbase/TcpClient.o

# target to build an object file
Etbase/TcpClient.cpp.o:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/TcpClient.cpp.o
.PHONY : Etbase/TcpClient.cpp.o

Etbase/TcpClient.i: Etbase/TcpClient.cpp.i

.PHONY : Etbase/TcpClient.i

# target to preprocess a source file
Etbase/TcpClient.cpp.i:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/TcpClient.cpp.i
.PHONY : Etbase/TcpClient.cpp.i

Etbase/TcpClient.s: Etbase/TcpClient.cpp.s

.PHONY : Etbase/TcpClient.s

# target to generate assembly for a file
Etbase/TcpClient.cpp.s:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/TcpClient.cpp.s
.PHONY : Etbase/TcpClient.cpp.s

Etbase/TcpServer.o: Etbase/TcpServer.cpp.o

.PHONY : Etbase/TcpServer.o

# target to build an object file
Etbase/TcpServer.cpp.o:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/TcpServer.cpp.o
.PHONY : Etbase/TcpServer.cpp.o

Etbase/TcpServer.i: Etbase/TcpServer.cpp.i

.PHONY : Etbase/TcpServer.i

# target to preprocess a source file
Etbase/TcpServer.cpp.i:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/TcpServer.cpp.i
.PHONY : Etbase/TcpServer.cpp.i

Etbase/TcpServer.s: Etbase/TcpServer.cpp.s

.PHONY : Etbase/TcpServer.s

# target to generate assembly for a file
Etbase/TcpServer.cpp.s:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/TcpServer.cpp.s
.PHONY : Etbase/TcpServer.cpp.s

Etbase/ThreadPool.o: Etbase/ThreadPool.cpp.o

.PHONY : Etbase/ThreadPool.o

# target to build an object file
Etbase/ThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/ThreadPool.cpp.o
.PHONY : Etbase/ThreadPool.cpp.o

Etbase/ThreadPool.i: Etbase/ThreadPool.cpp.i

.PHONY : Etbase/ThreadPool.i

# target to preprocess a source file
Etbase/ThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/ThreadPool.cpp.i
.PHONY : Etbase/ThreadPool.cpp.i

Etbase/ThreadPool.s: Etbase/ThreadPool.cpp.s

.PHONY : Etbase/ThreadPool.s

# target to generate assembly for a file
Etbase/ThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/ThreadPool.cpp.s
.PHONY : Etbase/ThreadPool.cpp.s

Etbase/Util.o: Etbase/Util.cpp.o

.PHONY : Etbase/Util.o

# target to build an object file
Etbase/Util.cpp.o:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Util.cpp.o
.PHONY : Etbase/Util.cpp.o

Etbase/Util.i: Etbase/Util.cpp.i

.PHONY : Etbase/Util.i

# target to preprocess a source file
Etbase/Util.cpp.i:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Util.cpp.i
.PHONY : Etbase/Util.cpp.i

Etbase/Util.s: Etbase/Util.cpp.s

.PHONY : Etbase/Util.s

# target to generate assembly for a file
Etbase/Util.cpp.s:
	$(MAKE) -f CMakeFiles/Etbase.dir/build.make CMakeFiles/Etbase.dir/Etbase/Util.cpp.s
.PHONY : Etbase/Util.cpp.s

test/client.o: test/client.cpp.o

.PHONY : test/client.o

# target to build an object file
test/client.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/test/client.cpp.o
.PHONY : test/client.cpp.o

test/client.i: test/client.cpp.i

.PHONY : test/client.i

# target to preprocess a source file
test/client.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/test/client.cpp.i
.PHONY : test/client.cpp.i

test/client.s: test/client.cpp.s

.PHONY : test/client.s

# target to generate assembly for a file
test/client.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/test/client.cpp.s
.PHONY : test/client.cpp.s

test/server.o: test/server.cpp.o

.PHONY : test/server.o

# target to build an object file
test/server.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/test/server.cpp.o
.PHONY : test/server.cpp.o

test/server.i: test/server.cpp.i

.PHONY : test/server.i

# target to preprocess a source file
test/server.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/test/server.cpp.i
.PHONY : test/server.cpp.i

test/server.s: test/server.cpp.s

.PHONY : test/server.s

# target to generate assembly for a file
test/server.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/test/server.cpp.s
.PHONY : test/server.cpp.s

test/test.o: test/test.cpp.o

.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... Server"
	@echo "... Client"
	@echo "... rebuild_cache"
	@echo "... Etbase"
	@echo "... Test"
	@echo "... Etbase/Epoll.o"
	@echo "... Etbase/Epoll.i"
	@echo "... Etbase/Epoll.s"
	@echo "... Etbase/Event.o"
	@echo "... Etbase/Event.i"
	@echo "... Etbase/Event.s"
	@echo "... Etbase/EventMap.o"
	@echo "... Etbase/EventMap.i"
	@echo "... Etbase/EventMap.s"
	@echo "... Etbase/EventQueue.o"
	@echo "... Etbase/EventQueue.i"
	@echo "... Etbase/EventQueue.s"
	@echo "... Etbase/Mutex.o"
	@echo "... Etbase/Mutex.i"
	@echo "... Etbase/Mutex.s"
	@echo "... Etbase/Reactor.o"
	@echo "... Etbase/Reactor.i"
	@echo "... Etbase/Reactor.s"
	@echo "... Etbase/Socket.o"
	@echo "... Etbase/Socket.i"
	@echo "... Etbase/Socket.s"
	@echo "... Etbase/String.o"
	@echo "... Etbase/String.i"
	@echo "... Etbase/String.s"
	@echo "... Etbase/TcpClient.o"
	@echo "... Etbase/TcpClient.i"
	@echo "... Etbase/TcpClient.s"
	@echo "... Etbase/TcpServer.o"
	@echo "... Etbase/TcpServer.i"
	@echo "... Etbase/TcpServer.s"
	@echo "... Etbase/ThreadPool.o"
	@echo "... Etbase/ThreadPool.i"
	@echo "... Etbase/ThreadPool.s"
	@echo "... Etbase/Util.o"
	@echo "... Etbase/Util.i"
	@echo "... Etbase/Util.s"
	@echo "... test/client.o"
	@echo "... test/client.i"
	@echo "... test/client.s"
	@echo "... test/server.o"
	@echo "... test/server.i"
	@echo "... test/server.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

